#pragma once
#include <stdint.h>
#include <IPAddress.h>

enum wl_status_t : uint8_t {
  WL_IDLE_STATUS = 0, WL_NO_SSID_AVAIL = 1, WL_SCAN_COMPLETED = 2,
  WL_CONNECTED = 3, WL_CONNECT_FAILED = 4, WL_CONNECTION_LOST = 5,
  WL_DISCONNECTED = 6, WL_NO_SHIELD = 255
};
enum wifi_mode_t : uint8_t { WIFI_OFF = 0, WIFI_STA = 1, WIFI_AP = 2, WIFI_AP_STA = 3 };
enum wifi_auth_mode_t : uint8_t {
  WIFI_AUTH_OPEN = 0, WIFI_AUTH_WEP, WIFI_AUTH_WPA_PSK, WIFI_AUTH_WPA2_PSK,
  WIFI_AUTH_WPA_WPA2_PSK, WIFI_AUTH_WPA2_ENTERPRISE, WIFI_AUTH_WPA3_PSK,
  WIFI_AUTH_WPA2_WPA3_PSK, WIFI_AUTH_WAPI_PSK, WIFI_AUTH_OWE,
  WIFI_AUTH_WPA3_ENT_192, WIFI_AUTH_MAX
};
enum wifi_power_t : int8_t {
  WIFI_POWER_19_5dBm = 78, WIFI_POWER_19dBm = 76, WIFI_POWER_18_5dBm = 74,
  WIFI_POWER_17dBm = 68, WIFI_POWER_15dBm = 60, WIFI_POWER_13dBm = 52,
  WIFI_POWER_11dBm = 44, WIFI_POWER_8_5dBm = 34, WIFI_POWER_7dBm = 28,
  WIFI_POWER_5dBm = 20, WIFI_POWER_2dBm = 8, WIFI_POWER_MINUS_1dBm = -4
};
enum arduino_event_id_t : uint8_t {
  ARDUINO_EVENT_WIFI_READY = 0, ARDUINO_EVENT_WIFI_SCAN_DONE,
  ARDUINO_EVENT_WIFI_STA_START, ARDUINO_EVENT_WIFI_STA_STOP,
  ARDUINO_EVENT_WIFI_STA_CONNECTED, ARDUINO_EVENT_WIFI_STA_DISCONNECTED,
  ARDUINO_EVENT_WIFI_STA_AUTHMODE_CHANGE, ARDUINO_EVENT_WIFI_STA_GOT_IP,
  ARDUINO_EVENT_WIFI_STA_GOT_IP6, ARDUINO_EVENT_WIFI_STA_LOST_IP,
  ARDUINO_EVENT_WIFI_AP_START, ARDUINO_EVENT_WIFI_AP_STOP,
  ARDUINO_EVENT_WIFI_AP_STACONNECTED, ARDUINO_EVENT_WIFI_AP_STADISCONNECTED,
  ARDUINO_EVENT_MAX = 255
};
using WiFiEvent_t = arduino_event_id_t;
struct WiFiEventInfo_t {
  uint16_t reason;
  IPAddress ip;
  uint8_t mac[6];
  WiFiEventInfo_t() : reason(0), ip(), mac{} {}
};
using WiFiEventCb = void (*)(WiFiEvent_t event);
using WiFiEventFuncCb = void (*)(WiFiEvent_t event, WiFiEventInfo_t info);
using wifi_event_id_t = uint32_t;
constexpr int16_t WIFI_SCAN_RUNNING = -1;
constexpr int16_t WIFI_SCAN_FAILED = -2;
